### PR TITLE
Key6oard warrior

### PR DESCRIPTION
**Pull request by key6oardWarrior**
Day 1 and Day 3 Labs

### CODE REVIEW

**Comment by SnoodTood** [comment]
Regarding the day 1 labs, I see that the included images are examples of flowcharts demonstrating computational thinking, but I'm not sure what the students are actually intended to do with the images. Would they be asked to come up with variations, or to think up their own flowcharts for other situations?

The day 3 labs look fine, although I think there might be a substantive typo in the Fizz Buzz Bazz description since it says to print "bazz" in two seperate circumstances.

**Comment by key6oardWarrior** [comment]
I will fix the typo and the student should make their own flow chart before seeing your flowchart. They can make it in whatever program they want. I used Word and just took a screenshot of it.

**Comment by key6oardWarrior** [comment]
If you think this is good now you can approve it, or give more feed back.

**Review by SnoodTood — APPROVED** [review]
All right, as long as we keep track of what to do with each lab, everything should work. Looks good.

**Comment by key6oardWarrior** [comment]
Lessons for days 1 and 3. Lesson one is flow charts lesson 2 is conditionals

**Pull request merged**
